### ISSUE TITLE
TypeError [ERR_MISSING_ARGS]: The "value" argument must be specified

### ISSUE THREAD

**Issue by Stateford** [idietmoran/twitch-api#11]
```
TypeError [ERR_MISSING_ARGS]: The "value" argument must be specified
    at validateHeader (_http_outgoing.js:501:11)
    at ClientRequest.setHeader (_http_outgoing.js:510:3)
    at new ClientRequest (_http_client.js:173:14)
    at Object.request (https.js:245:10)
    at Promise (D:\js\twitch-roulette\node_modules\twitch.tv-api\src\bin\request.js:44:29)
    at Promise._execute (D:\js\twitch-roulette\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (D:\js\twitch-roulette\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\js\twitch-roulette\node_modules\bluebird\js\release\promise.js:79:10)
    at Function.Request.https (D:\js\twitch-roulette\node_modules\twitch.tv-api\src\bin\request.js:42:12)
    at Promise (D:\js\twitch-roulette\node_modules\twitch.tv-api\src\bin\request.js:114:26)
    at Promise._execute (D:\js\twitch-roulette\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (D:\js\twitch-roulette\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\js\twitch-roulette\node_modules\bluebird\js\release\promise.js:79:10)
    at Function.Request.get (D:\js\twitch-roulette\node_modules\twitch.tv-api\src\bin\request.js:100:12)
    at Promise (D:\js\twitch-roulette\node_modules\twitch.tv-api\src\twitch.js:30:21)
    at Promise._execute (D:\js\twitch-roulette\node_modules\bluebird\js\release\debuggability.js:303:9)
```

Not sure what is causing this error, seems like headers are undefined. Only happens on 9.4.0+ from what I understand. Really frustrating that they break backwards compatibility so easily.

**Comment by AndrewBudziszek** [comment]
What was this issue?

**Comment by Stateford** [comment]
Are you having this issue? I believe it was fixed.

**Comment by AndrewBudziszek** [comment]
I was having the issue, but I got past it and forgot what I did. I'm that guy. My apologies!
